### ISSUE TITLE
RequestsJSONDecodeError

### ISSUE THREAD

**Issue by zuan35** [nilleb/voltalis-cli#1]
Bonjour Nilleb,

Je cherche à utiliser ton programme afin de faire remonter mes données Voltalis dans Jeedom.
Pour le moment je souhaite simplement executer le script pour voir le type d'information et le format que cela remonte pour après intégrer ces données sous Jeedom.

Je suis sous Debian 11 Bullseye (VM Freebox) et sous Python 3.9.
Je n'y connait pas grand chose en Python ou autres langages mais j'arrive un peu à comprendre les choses.

Voici ce que j’obtiens comme erreur :

> freebox@Debian:~$ python3 -m voltalis.cli EMAIL-LOGIN MOTDEPASSE
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 971, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/freebox/.local/lib/python3.9/site-packages/voltalis/cli.py", line 194, in <module>
>     main(username, password)
>   File "/home/freebox/.local/lib/python3.9/site-packages/voltalis/cli.py", line 36, in main
>     cli.login()
>   File "/home/freebox/.local/lib/python3.9/site-packages/voltalis/__init__.py", line 42, in login
>     self.token = Token(self.login_response.json())
>   File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 975, in json
>     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
> requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Je ne sais pas si tu as remarqué, mais il y a 2 versions de la page d'accueil. J'ai tenté de changer ces URL dans le fichier __init__.py mais sans résultats.

> https://myvoltalis.com/
> https://classic.myvoltalis.com/
Une fois sur le site, toutes les pages sont sous ce sous domaine : https://classic.myvoltalis.com/

Par avance, merci pour toute aide.

**Comment by nilleb** [comment]
Coucou!

Si tu as envie de déboguer un peu, tu peux changer le contenu de `/home/freebox/.local/lib/python3.9/site-packages/voltalis/__init__.py`, ligne 42
pour rajouter un "print(self.login_response.content)"
juste avant

ainsi tu verras la réponse du serveur.

je me note de rajouter un "mode verbeux" qui fasse ceci.

edit: l'explication est que la réponse n'est pas du JSON valide - probablement tu prends une page html en guise de réponse. p-ê que le endpoint n'est plus valable - je n'ai plus tout à fait essayé depuis le mois d'avril.

merci beaucoup pour ton retour - si tu souhaites contribuer, tu es le bienvenue!

**Comment by nilleb** [comment]
J'ai corrigé le login, j'espère ça pourra vous être utile.
