### ISSUE TITLE
Beta tests ?

### ISSUE THREAD

**Issue by jcoudrais** [nilleb/voltalis-cli#2]
Salut @nilleb toujours intéressé par voltalis ? Moi oui, si je peux aider pour tester...

**Comment by nilleb** [comment]
Récemment Voltalis a changé son interface.

Il y a des chances que tout ce module soit à refaire, étant donné qu'ils ont syphonné tous les programmes que j'avais renseigné dans l'ancienne appli. Le support client a simplement admis que tout était à reprogrammer, et à ma charge.

**Comment by nilleb** [comment]
@jcoudrais quel est exactement votre besoin?

**Comment by jcoudrais** [comment]
Salut, merci pour le retour ;-)
piloter la présence/absence plutot que programmation horaire par exemple (avec jeedom)

**Comment by nilleb** [comment]
si vous avez accès à l'UI de myvltalis et quelques notions de développement, ce sera facile avec les derniers changements que je viens de pousser. Pull Requests are welcome! :)

**Comment by jcoudrais** [comment]
> si vous avez accès à l'UI de myvltalis et quelques notions de développement, ce sera facile avec les derniers changements que je viens de pousser. Pull Requests are welcome! :)

Salut nilleb,
Merci bien pour cela, ça va mieux a priori mais même si j'ai accès à Myvltalis, ça plante :
```
 Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/voltalis/cli.py", line 194, in <module>
    main(username, password)
  File "/usr/local/lib/python3.7/dist-packages/voltalis/cli.py", line 36, in main
    cli.login()
  File "/usr/local/lib/python3.7/dist-packages/voltalis/__init__.py", line 42, in login
    self._log_response("/login.json", self.login_response)
  File "/usr/local/lib/python3.7/dist-packages/voltalis/__init__.py", line 54, in _log_response
    with open(f"dumps/response-{called}.bin", "wb") as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'dumps/response-login.bin'

```

Il doit pas manquer grand chose... Merci de ton aide

**Comment by nilleb** [comment]
Hello @jcoudrais !

Ce problème avait été fixé dans la 1.1.2:
https://github.com/nilleb/voltalis-cli/commit/c86fe369a3d2b74ac0a75b7c254f3945aeb8c023

Et dans la 1.2.0 vous avez aussi l'extraction des données de consommation dans un dataframe pandas ;)
